export const page_slides_option6 = {
  airQualityAndHealth: [
    {
      imageUrl: "/images/airQualityDC.jpg",
      imageAlt: "Air quality in Washington DC",
      title: "Air Quality in Washington DC",
      upperText: "Satellite monitoring of urban pollution",
      lowerText: "NASA's satellite data complements ground monitors to provide detailed air quality assessments, identifying pollution levels and trends in urban environments like Washington DC.",
    },
    {
      imageUrl: "/images/ozoneHealthEffects.jpg",
      imageAlt: "Health effects of ozone pollution",
      title: "Health Effects of Ozone",
      upperText: "Risks associated with ground-level ozone",
      lowerText: "Ground-level ozone causes respiratory issues, exacerbates asthma, and increases susceptibility to infections, underscoring the need for effective pollution control.",
    },
    {
      imageUrl: "/images/nitrogenDioxide.jpg",
      imageAlt: "Nitrogen dioxide pollution",
      title: "Nitrogen Dioxide Pollution",
      upperText: "Sources and environmental impact",
      lowerText: "Nitrogen dioxide from vehicle emissions and industrial activities contributes to smog formation and poses serious health risks, necessitating regulatory measures.",
    },
    {
      imageUrl: "/images/sulfurDioxide.jpg",
      imageAlt: "Sulfur dioxide emissions",
      title: "Sulfur Dioxide Emissions",
      upperText: "Environmental and health consequences",
      lowerText: "Sulfur dioxide contributes to acid rain, respiratory problems, and environmental degradation, highlighting the importance of emission reductions.",
    },
    {
      imageUrl: "/images/airPollutionSocioeconomic.jpg",
      imageAlt: "Socioeconomic factors and air pollution",
      title: "Socioeconomic Factors in Air Pollution",
      upperText: "Linking pollution to vulnerable communities",
      lowerText: "Air quality data combined with socioeconomic information reveal how pollution disproportionately affects marginalized communities, informing equitable policy interventions.",
    },
  ],
  naturalDisastersAndClimate: [
    {
      imageUrl: "/images/hurricaneSeason.jpg",
      imageAlt: "Active hurricane season",
      title: "Active Hurricane Season",
      upperText: "Link to ocean warming",
      lowerText: "Warmer ocean temperatures fuel more intense hurricanes, increasing the frequency and severity of these natural disasters due to climate change.",
    },
    {
      imageUrl: "/images/extremeHeatwave.jpg",
      imageAlt: "Heatwave impact",
      title: "Extreme Heatwaves",
      upperText: "Increasing frequency and intensity",
      lowerText: "Heatwaves are becoming more common and severe, posing health risks, straining energy resources, and affecting agricultural productivity.",
    },
    {
      imageUrl: "/images/floodingEvents.jpg",
      imageAlt: "Flooding due to heavy rainfall",
      title: "Flooding Events",
      upperText: "Triggered by intense precipitation",
      lowerText: "Extreme rainfall leads to flooding, causing property damage, loss of life, and long-term economic impacts, necessitating improved forecasting and infrastructure.",
    },
    {
      imageUrl: "/images/wildfireSeason.jpg",
      imageAlt: "Intense wildfire season",
      title: "Intense Wildfire Seasons",
      upperText: "Rising due to climate change",
      lowerText: "Climate change contributes to longer and more severe wildfire seasons, threatening ecosystems, air quality, and human communities.",
    },
    {
      imageUrl: "/images/droughtConditions.jpg",
      imageAlt: "Drought affecting agriculture",
      title: "Drought Conditions",
      upperText: "Impact on water resources and farming",
      lowerText: "Droughts reduce water availability, harm crops, and disrupt ecosystems, highlighting the need for sustainable water management and resilient agricultural practices.",
    },
  ],
  integratedSystemsAndSolutions: [
    {
      imageUrl: "/images/climateResilience.jpg",
      imageAlt: "Building climate resilience",
      title: "Building Climate Resilience",
      upperText: "Adapting to changing climates",
      lowerText: "Developing resilient infrastructure and communities helps mitigate the impacts of climate change, ensuring sustainability and safety in the face of environmental challenges.",
    },
    {
      imageUrl: "/images/technologyForClimate.jpg",
      imageAlt: "Technology solutions for climate",
      title: "Technology Solutions",
      upperText: "Innovating for a sustainable future",
      lowerText: "Advancements in technology, such as satellite monitoring and renewable energy, are crucial for tracking environmental changes and reducing human impact on the climate.",
    },
    {
      imageUrl: "/images/climatePolicy.jpg",
      imageAlt: "Global climate policy meeting",
      title: "Global Climate Policy",
      upperText: "Collaborative efforts to combat climate change",
      lowerText: "International agreements and policies are essential for coordinating efforts to reduce emissions, protect ecosystems, and promote sustainable development worldwide.",
    },
    {
      imageUrl: "/images/renewableEnergyGrowth.jpg",
      imageAlt: "Growth of renewable energy infrastructure",
      title: "Growth of Renewable Energy",
      upperText: "Scaling up sustainable energy",
      lowerText: "Expanding renewable energy infrastructure is vital for reducing greenhouse gas emissions, decreasing pollution, and transitioning to a sustainable energy future.",
    },
    {
      imageUrl: "/images/ecosystemRestoration.jpg",
      imageAlt: "Ecosystem restoration projects",
      title: "Ecosystem Restoration",
      upperText: "Healing and rebuilding natural systems",
      lowerText: "Restoring damaged ecosystems enhances biodiversity, sequesters carbon, and improves resilience against climate-related disruptions, supporting overall environmental health.",
    },
  ],
};
