export const page_slides_option4 = {
  sustainableDevelopment: [
    {
      imageUrl: "/images/renewableEnergySources.jpg",
      imageAlt: "Various renewable energy sources",
      title: "Renewable Energy Sources",
      upperText: "Diversifying energy production",
      lowerText: "Utilizing solar, wind, and other renewable sources reduces dependence on fossil fuels, lowering carbon emissions and pollution.",
    },
    {
      imageUrl: "/images/solarPanelsInstallation.jpg",
      imageAlt: "Installation of solar panels",
      title: "Solar Energy Implementation",
      upperText: "Harnessing solar insolation",
      lowerText: "Effective use of solar insolation data optimizes solar panel placement, enhancing energy capture and supporting sustainable energy initiatives.",
    },
    {
      imageUrl: "/images/windTurbines.jpg",
      imageAlt: "Wind turbines in a wind farm",
      title: "Wind Energy",
      upperText: "Capitalizing on wind patterns",
      lowerText: "Wind energy leverages global wind patterns to generate clean electricity, contributing to the reduction of greenhouse gas emissions.",
    },
    {
      imageUrl: "/images/energyEfficiency.jpg",
      imageAlt: "Energy-efficient buildings",
      title: "Energy Efficiency",
      upperText: "Reducing energy consumption",
      lowerText: "Implementing energy-efficient technologies and practices minimizes resource use, lowers emissions, and supports sustainable development goals.",
    },
    {
      imageUrl: "/images/renewableEnergyMap.jpg",
      imageAlt: "Global renewable energy map",
      title: "Global Renewable Energy Distribution",
      upperText: "Mapping renewable resources",
      lowerText: "Global maps of renewable energy potential guide policy-making and investment, ensuring effective deployment of sustainable energy solutions.",
    },
  ],
  ecosystemHealth: [
    {
      imageUrl: "/images/ndviVegetationHealth.jpg",
      imageAlt: "Healthy vegetation NDVI map",
      title: "Vegetation Health (NDVI)",
      upperText: "Assessing plant vitality",
      lowerText: "NDVI indices from MODIS data monitor vegetation health and coverage, essential for managing natural resources and agricultural productivity.",
    },
    {
      imageUrl: "/images/amazonRainforest.jpg",
      imageAlt: "Amazon rainforest",
      title: "Amazon Rainforest Health",
      upperText: "Impact of deforestation and dust fertilization",
      lowerText: "Satellite and field research track deforestation effects and the role of North African dust in fertilizing the Amazon, influencing global carbon cycles.",
    },
    {
      imageUrl: "/images/migrationPatterns.jpg",
      imageAlt: "Animal migration patterns",
      title: "Animal Migration Tracking",
      upperText: "Effects of environmental changes",
      lowerText: "Mapping animal migrations helps understand the impact of water sources, habitat loss, and climate change on wildlife populations.",
    },
    {
      imageUrl: "/images/cleanWaterMap.jpg",
      imageAlt: "Clean water sources map",
      title: "Clean Water Distribution",
      upperText: "Ensuring access to freshwater",
      lowerText: "Satellite data monitors waterway quality and distribution, vital for maintaining healthy ecosystems and supporting human communities.",
    },
    {
      imageUrl: "/images/forestFireImpact.jpg",
      imageAlt: "Forest affected by wildfire",
      title: "Forest Fire Impact",
      upperText: "Consequences for ecosystems",
      lowerText: "Wildfires alter forest structure, release greenhouse gases, and affect biodiversity, necessitating effective monitoring and management strategies.",
    },
  ],
  climateChangeImpact: [
    {
      imageUrl: "/images/arcticIceLoss.jpg",
      imageAlt: "Arctic ice loss over time",
      title: "Arctic Ice Loss",
      upperText: "Monitoring polar ice changes",
      lowerText: "Satellite observations track the rapid loss of ice in the Arctic and Antarctic, contributing to sea-level rise and altering global climate patterns.",
    },
    {
      imageUrl: "/images/glacialLakeOutburst.jpg",
      imageAlt: "Glacial lake outburst flood",
      title: "Glacial Lake Outburst Floods",
      upperText: "Sudden water surges from glaciers",
      lowerText: "Monitoring glacial lakes helps predict and mitigate dangerous floods caused by sudden water releases, protecting downstream communities.",
    },
    {
      imageUrl: "/images/snowpackLevels.jpg",
      imageAlt: "Snowpack levels in mountains",
      title: "Snowpack Monitoring",
      upperText: "Vital for water resources",
      lowerText: "Tracking snowpack levels in regions like the Sierra Nevada and Rockies is essential for managing freshwater supplies and predicting droughts.",
    },
    {
      imageUrl: "/images/seaLevelRise.jpg",
      imageAlt: "Global sea level rise graph",
      title: "Sea Level Rise",
      upperText: "Impact on coastal regions",
      lowerText: "Rising sea levels due to ice melt and thermal expansion threaten coastal infrastructure, ecosystems, and human settlements worldwide.",
    },
    {
      imageUrl: "/images/extremeWeatherEvents.jpg",
      imageAlt: "Extreme weather events collage",
      title: "Extreme Weather Events",
      upperText: "Increasing frequency and intensity",
      lowerText: "Climate change is linked to more frequent and severe weather events like floods, hurricanes, and heatwaves, necessitating resilient infrastructure and preparedness.",
    },
  ],
};
