export const page_slides_option3 = {
  airQualityAndPollution: [
    {
      imageUrl: "/images/airQualitySensors.jpg",
      imageAlt: "Air quality sensors in urban area",
      title: "Air Quality Sensors",
      upperText: "Monitoring pollutants in real-time",
      lowerText: "Advanced sensors aboard satellites and aircraft measure pollutants like NO2 and SO2, providing comprehensive air quality data for urban and rural areas.",
    },
    {
      imageUrl: "/images/groundOzone.jpg",
      imageAlt: "Ground-level ozone effects",
      title: "Ground-Level Ozone",
      upperText: "Health risks and environmental impact",
      lowerText: "Ozone at ground level causes respiratory issues and damages vegetation, necessitating stringent pollution control measures.",
    },
    {
      imageUrl: "/images/ozoneLayerStratosphere.jpg",
      imageAlt: "Stratospheric ozone layer",
      title: "Stratospheric Ozone",
      upperText: "Protecting life from UV radiation",
      lowerText: "The ozone layer in the stratosphere absorbs harmful UV-B radiation, safeguarding ecosystems and human health from its damaging effects.",
    },
    {
      imageUrl: "/images/carbonMonoxideLevels.jpg",
      imageAlt: "Carbon monoxide concentration map",
      title: "Carbon Monoxide Levels",
      upperText: "Tracking CO emissions globally",
      lowerText: "Monitoring CO helps in understanding its role in atmospheric chemistry, including the depletion of OH radicals and its contribution to climate change.",
    },
    {
      imageUrl: "/images/airPollutionMap.jpg",
      imageAlt: "Global air pollution map",
      title: "Global Air Pollution",
      upperText: "Spatial distribution of pollutants",
      lowerText: "Global maps of air pollution assist in identifying hotspots, assessing trends, and formulating international policies to improve air quality.",
    },
  ],
  wildfireAndAtmosphericImpact: [
    {
      imageUrl: "/images/wildfireDetection.jpg",
      imageAlt: "Detecting wildfires via satellite",
      title: "Wildfire Detection",
      upperText: "Early identification and monitoring",
      lowerText: "Satellite-based detection systems like MODIS provide timely information on wildfire locations and intensities, aiding in disaster response and management.",
    },
    {
      imageUrl: "/images/smokeImpact.jpg",
      imageAlt: "Smoke impact on atmosphere",
      title: "Smoke Impact",
      upperText: "Aerosols affecting climate and air quality",
      lowerText: "Smoke aerosols from wildfires influence cloud formation, surface temperatures, and air quality, with both warming and cooling effects on the climate.",
    },
    {
      imageUrl: "/images/wildfireEmission.jpg",
      imageAlt: "Greenhouse gas emissions from wildfires",
      title: "Wildfire Emissions",
      upperText: "Contributing to greenhouse gases",
      lowerText: "Wildfires release significant amounts of CO2 and other greenhouse gases, exacerbating global warming and altering atmospheric composition.",
    },
    {
      imageUrl: "/images/forestFertilization.jpg",
      imageAlt: "Dust fertilizing forests",
      title: "Dust Fertilization",
      upperText: "North African dust and Amazon rainforest",
      lowerText: "Dust from North Africa fertilizes the Amazon rainforest, supporting vegetation growth, but climate change threatens this critical nutrient supply.",
    },
    {
      imageUrl: "/images/wildfireClimateFeedback.jpg",
      imageAlt: "Climate feedback from wildfires",
      title: "Climate Feedback Loops",
      upperText: "Wildfires influencing climate systems",
      lowerText: "Increased wildfire activity alters climate feedback loops by changing surface albedo, releasing greenhouse gases, and modifying atmospheric chemistry.",
    },
  ],
  temperatureAndCarbonCycle: [
    {
      imageUrl: "/images/globalTempAnomalyMap.jpg",
      imageAlt: "Global temperature anomaly map",
      title: "Global Temperature Anomaly",
      upperText: "Identifying temperature deviations",
      lowerText: "Temperature anomaly maps highlight regions experiencing significant warming or cooling, crucial for tracking climate change progression.",
    },
    {
      imageUrl: "/images/carbonCycleDiagram.jpg",
      imageAlt: "Carbon cycle illustration",
      title: "Carbon Cycle",
      upperText: "Interplay between emissions and sequestration",
      lowerText: "The carbon cycle illustrates the movement of carbon through the atmosphere, oceans, and biosphere, essential for understanding climate dynamics.",
    },
    {
      imageUrl: "/images/solarInsolationEffect.jpg",
      imageAlt: "Solar insolation effects on climate",
      title: "Solar Insolation Effects",
      upperText: "Driving Earth's energy balance",
      lowerText: "Solar insolation influences global temperature distributions, weather patterns, and the overall energy balance of the planet.",
    },
    {
      imageUrl: "/images/seaSurfaceTempMap.jpg",
      imageAlt: "Sea surface temperature map",
      title: "Sea Surface Temperature",
      upperText: "Ocean's role in climate regulation",
      lowerText: "Sea surface temperatures affect weather systems, marine ecosystems, and the global climate by influencing heat distribution and ocean currents.",
    },
    {
      imageUrl: "/images/landOceanTempComparison.jpg",
      imageAlt: "Comparison of land and ocean temperatures",
      title: "Land vs. Ocean Temperatures",
      upperText: "Differential warming impacts",
      lowerText: "Land and ocean temperatures respond differently to climate change, with oceans acting as heat sinks and influencing global temperature trends.",
    },
  ],
};
